# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrey/CompPrac/second_task

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrey/CompPrac/second_task

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrey/CompPrac/second_task/CMakeFiles /home/andrey/CompPrac/second_task/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrey/CompPrac/second_task/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game-knights

# Build rule for target.
game-knights: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game-knights
.PHONY : game-knights

# fast build rule for target.
game-knights/fast:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/build
.PHONY : game-knights/fast

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/Game.cpp.s
.PHONY : Game.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/main.cpp.s
.PHONY : main.cpp.s

support/Token.o: support/Token.cpp.o
.PHONY : support/Token.o

# target to build an object file
support/Token.cpp.o:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/support/Token.cpp.o
.PHONY : support/Token.cpp.o

support/Token.i: support/Token.cpp.i
.PHONY : support/Token.i

# target to preprocess a source file
support/Token.cpp.i:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/support/Token.cpp.i
.PHONY : support/Token.cpp.i

support/Token.s: support/Token.cpp.s
.PHONY : support/Token.s

# target to generate assembly for a file
support/Token.cpp.s:
	$(MAKE) -f CMakeFiles/game-knights.dir/build.make CMakeFiles/game-knights.dir/support/Token.cpp.s
.PHONY : support/Token.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... game-knights"
	@echo "... rebuild_cache"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... support/Token.o"
	@echo "... support/Token.i"
	@echo "... support/Token.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

